const elements = [
  { number: 1, symbol: "H", name: "水素" },
  { number: 2, symbol: "He", name: "ヘリウム" },
  { number: 3, symbol: "Li", name: "リチウム" },
  { number: 4, symbol: "Be", name: "ベリリウム" },
  { number: 5, symbol: "B", name: "ホウ素" },
  { number: 6, symbol: "C", name: "炭素" },
  { number: 7, symbol: "N", name: "窒素" },
  { number: 8, symbol: "O", name: "酸素" },
  { number: 9, symbol: "F", name: "フッ素" },
  { number: 10, symbol: "Ne", name: "ネオン" },
  { number: 11, symbol: "Na", name: "ナトリウム" },
  { number: 12, symbol: "Mg", name: "マグネシウム" },
  { number: 13, symbol: "Al", name: "アルミニウム" },
  { number: 14, symbol: "Si", name: "ケイ素" },
  { number: 15, symbol: "P", name: "リン" },
  { number: 16, symbol: "S", name: "硫黄" },
  { number: 17, symbol: "Cl", name: "塩素" },
  { number: 18, symbol: "Ar", name: "アルゴン" },
  { number: 19, symbol: "K", name: "カリウム" },
  { number: 20, symbol: "Ca", name: "カルシウム" },
  { number: 25, symbol: "Mn", name: "マンガン" },
  { number: 26, symbol: "Fe", name: "鉄" },
  { number: 29, symbol: "Cu", name: "銅" },
  { number: 30, symbol: "Zn", name: "亜鉛" },
  { number: 35, symbol: "Br", name: "臭素" },
  { number: 47, symbol: "Ag", name: "銀" },
  { number: 53, symbol: "I", name: "ヨウ素" },
  { number: 78, symbol: "Pt", name: "白金" },
  { number: 79, symbol: "Au", name: "金" },
  { number: 82, symbol: "Pb", name: "鉛" }
];

// 以降も含めた完全版は、同じフォルダの script.js に保存済みです。
